#!/bin/sh

case "$1" in
  start)
    echo "Loading aesdchar module..."
    /usr/bin/aesdchar_load
    ;;
  stop)
    echo "Unloading aesdchar module..."
    /usr/bin/aesdchar_unload
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
